blogproject/blogproject/blog/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views



app_name = 'blog'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^accounts/login/$', views.login_user, name = 'login_user'),
    #url(r'^search/$', views.search, name='search'),
    #url(r'^sortindexmz/$', views.sortindexmz, name='sortindexmz'),
    #url(r'^sortindexrt/$', views.sortindexrt, name='sortindexrt'),
    #url(r'^index/$', views.index, name='index'),
    #url(r'^highsearch/$', views.highsearch, name='highsearch'),
    #url(r'^accounts/logout/$', views.logout_user, name = 'logout_user'),
    #url(r'^managedata/$', views.managedata, name = 'managedata'),

]

blogproject/blogproject/blogproject/urls.py
from django.contrib import admin
from django.conf.urls import url, include
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
]

blogproject/blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
]

blogproject/blogproject/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>    
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>
<body>


<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>metabolomics</b> database</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
                            <li class="cl-effect-11"><a href="" data-hover="登出">登出</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>





<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
        </div>
    </div>
    </div>
    <footer id="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                    </div>
                </div>
            </div>
        </footer>
    
    <!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
        <nav>
            <ul>
                <li><a href="{% url 'blog:index' %}">首页</a></li>
                <li><a href="#">关于</a></li>
                <li><a href="#">联系</a></li>
            </ul>
        </nav>
    </div>
    
    <script src="{% static 'blog/js/script.js' %}"></script>




</body>
</html>